name: Test
on:
  # Enable manually triggering this workflow via the API or web UI
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
        GOLANG_CI_VERSION: "1.41.1"
        GO111MODULE: 'on'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Install golangci-lint
        working-directory: /tmp
        run: go install "github.com/golangci/golangci-lint/cmd/golangci-lint@v$GOLANG_CI_VERSION"
      - name: Run linters
        run: |
          golangci-lint run --out-format=tab ./...

  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Run tests
        run: |
          set -x
          go version
          export GOMAXPROCS=2
          go test -p 2 -race -timeout 60s ./...
